:concurrency: <%= ENV["SIDEKIQ_WORKERS"] || 1 %>
development:
  :queues:
    - development.default
staging:
  :queues:
    - staging.default
production:
  :queues:
    - production.default
:queues:
  - default
